version: "2"
services:
  couchdb:
    image: klaemo/couchdb:2.0
  web:
    build: .
    command: node index.js
    volumes:
      - "./:/src/app"
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      APP_ENV: local
      COUCH_URL: http://couchdb:5984
      COUCH_DB_NAME: lunchwheel-local
    depends_on: 
      - couchdb